### ISSUE TITLE
Docker build is failing with `ENOENT`

### ISSUE THREAD

**Issue by lexisother** [FyraLabs/raboneko#8]
`pnpm install` runs `git ls-remote https://github.com/dmitmel/eslint-config-dmitmel.git HEAD` to get the latest commit of a git dependency and is somehow failing. Please investigate!

**Comment by lleyton** [comment]
Fixed in https://github.com/FyraLabs/raboneko/commit/e86bc199654bd89515fea957b1ebcf81b8bafcc9
